import test from 'node:test';
import assert from 'node:assert/strict';
import { HerculesReferenceService } from '../src/service.js';
import { decide } from '../src/decision.js';
import { ReferenceStateStore, ConcurrencyError, IntegrityError, NamespaceError } from '../src/state.js';
import { runFrozenFixture } from '../src/frozen-corpus-adapter.js';
const base=(events=[])=>({clientNamespace:'client:test-001',intakeSnapshotId:'intake:v2:001',activePlanVersionId:'plan:v1',sourceSchemaVersion:'intake-v2',activeGates:[],trackEvents:events});
const evt=(id,type,extra={})=>({eventId:id,namespace:'client:test-001',type,timestamp:'2026-08-27T12:00:00Z',...extra});
test('normal case maintains plan',()=>assert.equal(decide(base()).authorityClass,'MAINTAIN'));
test('missing feedback stays UNKNOWN and prompts',()=>assert.equal(decide(base([evt('e1','DECISION_RELEVANT_FEEDBACK_MISSING')])).authorityClass,'AUTO_PROMPT'));
test('new safety signal holds affected scope',()=>assert.equal(decide(base([evt('e2','NEW_PAIN',{affectedScope:'TRAIN:LOWER_BODY'})])).authorityClass,'HOLD_AFFECTED_SCOPE'));
test('pre-approved option is bounded, not new prescription',()=>assert.equal(decide(base([evt('e3','PREAPPROVED_OPTION_REQUEST',{approvedOptionId:'sub:leg-press'})])).authorityClass,'BOUNDED_IN_PLAN'));
test('material change never auto-activates',()=>assert.equal(decide(base([evt('e4','MATERIAL_CHANGE_REQUEST',{proposedPlanDiff:{frequency:'4->5'}})])).authorityClass,'PROPOSE_FOR_REVIEW'));
test('unexpected evaluator metadata is rejected',()=>assert.throws(()=>decide({...base(),expectedOutcome:'PASS'}),/unexpected prediction field|evaluator field/));
test('foreign namespace event is rejected',()=>assert.throws(()=>decide(base([{...evt('e5','NEW_PAIN'),namespace:'client:other'}])),/namespace mismatch/));
test('safety resolution requires matching episode and human/qualified authority',()=>{const svc=new HerculesReferenceService('client:test-001');const d=svc.evaluate(base([evt('e6','NEW_PAIN',{affectedScope:'TRAIN'})]));const gate=d.activeGates.at(-1);const wrong=svc.resolve(evt('r1','RESOLUTION',{targetEpisodeId:gate.gateEpisodeId,resolutionType:'SAFETY_REVIEW_RESOLVED',sourceAuthority:'SYSTEM'}));assert.equal(wrong.accepted,false);const ok=svc.resolve(evt('r2','RESOLUTION',{targetEpisodeId:gate.gateEpisodeId,resolutionType:'SAFETY_REVIEW_RESOLVED',sourceAuthority:'QUALIFIED_PROFESSIONAL'}));assert.equal(ok.accepted,true);assert.equal(ok.state.openGates.length,0)});
test('restart preserves trusted state',()=>{const svc=new HerculesReferenceService('client:test-001');svc.evaluate(base([evt('e7','NEW_PAIN')]));const restored=new HerculesReferenceService('client:test-001',svc.snapshot());assert.equal(restored.store.read().openGates.length,1)});
test('tampered snapshot fails closed',()=>{const store=new ReferenceStateStore('client:test-001');const snap=store.snapshot();snap.revision=999;assert.throws(()=>new ReferenceStateStore('client:test-001',snap),IntegrityError)});
test('stale writer is rejected by CAS',()=>{const store=new ReferenceStateStore('client:test-001');const old=store.read().commitId;store.apply({expectedBaseCommitId:old,namespace:'client:test-001'});assert.throws(()=>store.apply({expectedBaseCommitId:old,namespace:'client:test-001'}),ConcurrencyError)});
test('foreign namespace state mutation is rejected',()=>{const store=new ReferenceStateStore('client:test-001');assert.throws(()=>store.apply({namespace:'client:other'}),NamespaceError)});
test('frozen-corpus adapter keeps expected evaluation outside prediction input',()=>{const r=runFrozenFixture({fixtureId:'fx-001',predictionInput:base([evt('e8','NEW_PAIN',{affectedScope:'TRAIN'})]),expectedEvaluation:{authorityClass:'HOLD_AFFECTED_SCOPE',affectedScope:'TRAIN',ruleIds:['TE2-05']}});assert.equal(r.pass,true)});
