import test from "node:test";
import assert from "node:assert/strict";
import { decide } from "../src/engine.js";
import { DecisionInputSchema } from "../src/schema.js";

function baseInput(overrides = {}) { return { client_namespace:"client-war2-001", intake_snapshot_id:"intake-war2-001", active_plan_version_id:"plan-v1", source_schema_version:"intake-v2", event_timestamp:"2026-09-02T19:00:00Z", ...overrides }; }
function evt(id,type,extra={}) { return { event_id:id, namespace:"client-war2-001", timestamp:"2026-09-02T19:01:00Z", type, ...extra }; }

test("RC-34 consent revocation stops personalization before safety/event processing",()=>{ const result=decide(baseInput({personalization_consent:"REVOKED",track_events:[evt("s1","safety",{safety_kind:"PAIN",description:"new pain",affected_scope:["TRAIN"]})]})); assert.equal(result.authority_class,"HOLD_AFFECTED_SCOPE"); assert.deepEqual(result.affected_scope,["PERSONALIZATION"]); assert.equal(result.state.open_gates.length,0); assert.ok(result.rule_ids.includes("RC-34")); });
test("RC-34 unknown consent prompts rather than inferring permission",()=>{ const result=decide(baseInput({personalization_consent:"UNKNOWN"})); assert.equal(result.authority_class,"AUTO_PROMPT"); assert.deepEqual(result.requested_feedback,["personalization consent"]); });
test("RC-41 partial workout logs without becoming full completion",()=>{ const result=decide(baseInput({track_events:[evt("c1","completion",{action_id:"workout-1",outcome:"PARTIAL",completed_portion:"3 of 5 exercises"})]})); assert.equal(result.authority_class,"AUTO_LOG"); assert.ok(result.rule_ids.includes("RC-41")); });
test("RC-41 moved workout requires original linkage",()=>{ assert.throws(()=>decide(baseInput({track_events:[evt("c2","completion",{action_id:"workout-new",outcome:"MOVED"})]}))); const linked=decide(baseInput({track_events:[evt("c3","completion",{action_id:"workout-new",outcome:"MOVED",original_action_id:"workout-original"})]})); assert.equal(linked.authority_class,"AUTO_LOG"); });

test("RC-42 valid substitution parses before decision execution",()=>{ const input=baseInput({track_events:[evt("n-debug","nutrition_actual",{planned_meal_id:"meal-1",outcome:"SUBSTITUTED",actual_food:"chicken bowl",context:"work"})]}); const parsed=DecisionInputSchema.safeParse(input); assert.equal(parsed.success,true,parsed.success?"":JSON.stringify(parsed.error.issues)); });
test("RC-42 substituted meal requires confirmed actual food",()=>{ assert.throws(()=>decide(baseInput({track_events:[evt("n1","nutrition_actual",{planned_meal_id:"meal-1",outcome:"SUBSTITUTED"})]}))); const result=decide(baseInput({track_events:[evt("n2","nutrition_actual",{planned_meal_id:"meal-1",outcome:"SUBSTITUTED",actual_food:"chicken bowl",context:"work"})]})); assert.equal(result.authority_class,"AUTO_LOG"); assert.ok(result.rule_ids.includes("RC-42")); });
test("RC-42 allergy conflict opens NOURISH safety hold",()=>{ const result=decide(baseInput({track_events:[evt("n3","nutrition_actual",{planned_meal_id:"meal-1",outcome:"SUBSTITUTED",actual_food:"restaurant dish",allergy_conflict:true})]})); assert.equal(result.authority_class,"HOLD_AFFECTED_SCOPE"); assert.deepEqual(result.affected_scope,["NOURISH"]); assert.equal(result.active_gates[0].gate_type,"SAFETY_NUTRITION_ALLERGY"); });
test("RC-36 confirmed goal change creates versioned proposal",()=>{ const result=decide(baseInput({track_events:[evt("g1","goal_change",{new_primary_goal:"strength",confirmed:true,reason:"priority changed"})]})); assert.equal(result.authority_class,"PROPOSE_FOR_REVIEW"); assert.equal(result.proposed_plan_diff.primary_goal.to,"strength"); assert.ok(result.rule_ids.includes("RC-36")); });
test("RC-39 minor body-composition request remains policy-gated",()=>{ const result=decide(baseInput({client_context:{age:16,request_type:"BODY_COMPOSITION",minor_policy_status:"NOT_APPROVED"}})); assert.equal(result.authority_class,"PROPOSE_FOR_REVIEW"); assert.deepEqual(result.affected_scope,["SCOPE:MINOR_BODY_COMPOSITION"]); assert.ok(result.rule_ids.includes("RC-39")); });
test("RC-35 repeated confirmed observations become learning candidate without changing plan",()=>{ const result=decide(baseInput({track_events:[evt("l1","learning_observation",{learning_key:"preferred_duration",value:"30m",confirmed:true}),evt("l2","learning_observation",{learning_key:"preferred_duration",value:"30m",confirmed:true})]})); assert.equal(result.authority_class,"AUTO_LOG"); assert.deepEqual(result.evidence_event_ids,["l1","l2"]); assert.ok(result.rule_ids.includes("RC-35")); assert.equal(result.state.active_plan_version_id,"plan-v1"); });
test("RC-37/38 re-entry or shared-resource reality creates proposal",()=>{ const reentry=decide(baseInput({track_events:[evt("r1","reality_change",{domain:"SCHEDULE",description:"Return after interruption; re-entry into training is needed"})]})); assert.equal(reentry.authority_class,"PROPOSE_FOR_REVIEW"); assert.ok(reentry.rule_ids.includes("RC-37")); const shared=decide(baseInput({track_events:[evt("r2","reality_change",{domain:"EQUIPMENT",description:"Home equipment is shared and not reliably available"})]})); assert.equal(shared.authority_class,"PROPOSE_FOR_REVIEW"); assert.ok(shared.rule_ids.includes("RC-38")); });
