import { randomUUID } from 'node:crypto';
import { Authority, IMPLEMENTATION_VERSION, CONTRACT_VERSION, validatePredictionInput } from './contracts.js';
const SAFETY_TYPES=new Set(['NEW_PAIN','WORSENING_PAIN','CONCERNING_SYMPTOM','PROFESSIONAL_RESTRICTION','SAFETY_FLAG']);
const result=(authorityClass,rationale,extras={})=>({decisionId:randomUUID(),authorityClass,affectedScope:extras.affectedScope??'GLOBAL',rationale,evidenceEventIds:extras.evidenceEventIds??[],activeGates:extras.activeGates??[],requestedFeedback:extras.requestedFeedback??[],proposedPlanDiff:extras.proposedPlanDiff??null,ruleIds:extras.ruleIds??[],implementationVersion:IMPLEMENTATION_VERSION,contractVersion:CONTRACT_VERSION});
const openSafetyGate=e=>({gateEpisodeId:`gate:${e.eventId}`,gateType:'SAFETY_HOLD',status:'OPEN',affectedScope:e.affectedScope||'AFFECTED_SCOPE_UNKNOWN',sourceEventId:e.eventId,openedAt:e.timestamp,resolutionRequirement:'MATCHING_HUMAN_OR_QUALIFIED_REVIEW',namespace:e.namespace});
export function decide(rawInput){
 const input=validatePredictionInput(rawInput),openGates=input.activeGates.filter(g=>g.status==='OPEN'),events=[...input.trackEvents];
 const safety=events.find(e=>SAFETY_TYPES.has(e.type));if(safety){const gate=openSafetyGate(safety);return result(Authority.HOLD_AFFECTED_SCOPE,`Safety-relevant event ${safety.eventId} requires affected-scope hold/review; no diagnosis or automatic release.`,{affectedScope:gate.affectedScope,evidenceEventIds:[safety.eventId],activeGates:[...openGates,gate],ruleIds:['TE2-05','TE2-11']})}
 if(openGates.some(g=>g.gateType==='SAFETY_HOLD')) return result(Authority.HOLD_AFFECTED_SCOPE,'An unresolved safety gate remains controlling; elapsed time, silence, or unrelated performance cannot release it.',{affectedScope:openGates.find(g=>g.gateType==='SAFETY_HOLD').affectedScope,activeGates:openGates,ruleIds:['TE2-05','TE2-11','TE2-12']});
 const material=events.find(e=>e.type==='MATERIAL_CHANGE_REQUEST');if(material) return result(Authority.PROPOSE_FOR_REVIEW,'Requested change is material and cannot auto-activate.',{evidenceEventIds:[material.eventId],proposedPlanDiff:material.proposedPlanDiff??{status:'NEEDS_HUMAN_REVIEW'},ruleIds:['TE2-10','TE2-15']});
 const bounded=events.find(e=>e.type==='PREAPPROVED_OPTION_REQUEST');if(bounded){if(!bounded.approvedOptionId) return result(Authority.AUTO_PROMPT,'Pre-approved option mapping is ambiguous or missing.',{evidenceEventIds:[bounded.eventId],requestedFeedback:['approvedOptionId'],ruleIds:['TE2-09','TE2-12']});return result(Authority.BOUNDED_IN_PLAN,`Execute already-approved option ${bounded.approvedOptionId}; this does not create a new prescription.`,{evidenceEventIds:[bounded.eventId],ruleIds:['TE2-09']})}
 const missing=events.find(e=>e.type==='DECISION_RELEVANT_FEEDBACK_MISSING');if(missing) return result(Authority.AUTO_PROMPT,'Decision-relevant feedback is not observed; preserve UNKNOWN rather than inferring success or failure.',{evidenceEventIds:[missing.eventId],requestedFeedback:missing.requestedFeedback??['decision_relevant_feedback'],ruleIds:['TE2-01','TE2-12','TE2-13']});
 return result(Authority.MAINTAIN,'No explicit input justifies a material or bounded change; maintain the current approved plan.',{ruleIds:['TE2-01','TE2-13']});
}
export function classifyResolution(event,openGates){if(event.type!=='RESOLUTION') return {processable:false,reason:'not a resolution event'};const target=openGates.find(g=>g.gateEpisodeId===event.targetEpisodeId);if(!target) return {processable:false,reason:'target episode not open'};if(target.namespace&&target.namespace!==event.namespace) return {processable:false,reason:'namespace mismatch'};if(target.gateType==='SAFETY_HOLD'){if(!['HUMAN_REVIEWER','QUALIFIED_PROFESSIONAL'].includes(event.sourceAuthority)) return {processable:false,reason:'safety hold requires human/qualified authority'};if(event.resolutionType!=='SAFETY_REVIEW_RESOLVED') return {processable:false,reason:'resolution type does not match safety gate'}}return {processable:true,targetEpisodeId:target.gateEpisodeId}}
